#
# Copyright (C) 2008-2026 The OpenWrt Project
# Copyright (C) 2026 Manfred Jaider <masmbit@users.noreply.github.com>
#
# This is free software, licensed under the Apache License, Version 2.0.
# See /LICENSE for more information.
#

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-openvpn
PKG_VERSION:=2.0.0
PKG_RELEASE:=1
PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Manfred Jaider <masmbit@users.noreply.github.com>

LUCI_TITLE:=LuCI support for OpenVPN server and client configuration
LUCI_DEPENDS:=+luci-base +openvpn +openssl-util +firewall4 +coreutils
LUCI_PKGARCH:=all

define Package/$(PKG_NAME)/description
  This package provides an easy web interface to configure OpenVPN servers and
  clients quickly. With the built-in key generator, wizard, and DDNS, your VPN
  is up and running immediately. It replaces the old interface with a modern
  design optimized for current OpenWrt builds.
endef

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature

