#
# Copyright (C) 2008-2026 The OpenWrt Project
# Copyright (C) 2026 masmbit
#
# This is free software, licensed under the Apache License, Version 2.0.
#

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-openvpn
PKG_VERSION:=2.0.0
PKG_RELEASE:=1
PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Manfred Jaider <masmbit@users.noreply.github.com>

LUCI_TITLE:=LuCI support for OpenVPN server and client configuration
LUCI_DEPENDS:=+luci-base +openvpn-openssl +openssl-util +nftables +coreutils
LUCI_PKGARCH:=all

LUCI_DESCRIPTION:=This package provides an easy-to-use web interface for simple configuration \
	of OpenVPN server and client instances with key generator and connection wizard. \
	It is the replacement of the old, unsupported LuCI interface, delivering a \
	completely modernized design optimized for current OpenWrt builds.

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
