# Modern OpenVPN Client Configuration Instance

# --- Connection Mode ---
client
dev tun
proto udp

# --- Network & IP Management ---
remote 127.0.0.1 1194
float

# --- Certificates & Keys ---
ca /etc/openvpn/keys/ca_default.crt
cert /etc/openvpn/keys/server_default.crt
key /etc/openvpn/keys/server_default.key

# --- Hardening & Security ---
tls-crypt /etc/openvpn/keys/tls-crypt_default.key
tls-groups secp256r1
cipher AES-256-GCM
data-ciphers AES-256-GCM:AES-128-GCM

# --- Verification & Logging ---
resolv-retry infinite
nobind
persist-key
persist-tun
#remote-cert-tls server
verb 3
